#!/usr/bin/env ts-node

/**
 * Preview daily quotes - useful for testing and seeing upcoming quotes
 * Usage: npx ts-node preview-quotes.ts [number_of_days]
 */

import { getQuoteOfTheDay, formatQuote, getQuoteCount } from './lib/utils/daily-quotes';

// Get number of days from command line, default to 7
const daysToShow = parseInt(process.argv[2] || '7', 10);

const counts = getQuoteCount();

console.log(`\n📜 Daily Quotes Preview\n`);
console.log(`📚 Hardcoded quotes: ${counts.hardcoded}`);
console.log(`🤖 Claude-generated quotes: ${counts.generated}`);
console.log(`✨ Total quotes in rotation: ${counts.total}\n`);
console.log('═'.repeat(80));

// Show today's quote
const today = new Date();
console.log(`\n🌟 TODAY'S QUOTE (${today.toLocaleDateString()}):\n`);
console.log(formatQuote(getQuoteOfTheDay(today)));
console.log('\n' + '─'.repeat(80));

// Show upcoming quotes
if (daysToShow > 1) {
  console.log(`\n📅 UPCOMING QUOTES (next ${daysToShow - 1} days):\n`);
  
  for (let i = 1; i < daysToShow; i++) {
    const date = new Date();
    date.setDate(date.getDate() + i);
    const quote = getQuoteOfTheDay(date);
    
    console.log(`\nDay ${i} - ${date.toLocaleDateString()}:`);
    console.log(`"${quote.text}"`);
    console.log(`— ${quote.author}${quote.title ? `, ${quote.title}` : ''}`);
    console.log('─'.repeat(80));
  }
}

console.log(`\n✨ Total quotes in rotation: ${counts.total}`);
console.log(`📊 Full cycle repeats every ${counts.total} days (~${(counts.total / 30).toFixed(1)} months)`);
if (counts.generated > 0) {
  console.log(`🤖 ${counts.generated} quotes generated by Claude for variety\n`);
} else {
  console.log(`💡 Run 'npx ts-node manage-quotes.ts generate 50' to add Claude-generated quotes\n`);
}

